name: core_client
description: Core Client Package (HTTP/Dio Infrastructure)
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  meta: ^1.17.0
  dio: ^5.0.0
  core_shared:
    path: ../core_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
