name: core_client
description: Core Client Package (HTTP/Dio Infrastructure)
publish_to: none
version: 1.0.0

repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.17.0
  dio: ^5.9.0
  core_shared:
    path: ../core_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
