name: ems_app_v1
description: "A new Flutter project."
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^1.3.2
  dio: ^5.9.0
  core_shared: ^1.1.0
  core_ui: ^1.1.0
  localizations_ui: ^1.1.0
  design_system_shared: ^1.1.0
  design_system_ui: ^1.1.0
  auth_ui: ^1.1.0
  auth_client: ^1.1.0
  user_ui: ^1.1.0
  user_client: ^1.1.0
  tag_ui: ^1.1.0
  tag_client: ^1.1.0
  notebook_ui: ^1.1.0
  notebook_client: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  envied_generator: ^1.3.2

flutter:
  uses-material-design: true
