name: ems_app_v1
description: "A new Flutter project."
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^1.3.2
  dio: ^5.9.0
  core_shared: ^1.1.0
  core_ui: ^1.1.0
  localizations_ui: ^1.1.0
  design_system_shared: ^1.1.0
  design_system_ui: ^1.1.0
  auth_ui: ^1.1.0
  auth_client: ^1.1.0
  user_ui: ^1.1.0
  user_client: ^1.1.0
  tag_ui: ^1.1.0
  tag_client: ^1.1.0
  notebook_ui: ^1.1.0
  notebook_client: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  envied_generator: ^1.3.2
  icons_launcher: ^3.0.3
  names_launcher: ^0.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

#dart run icons_launcher:create
icons_launcher:
  image_path: "assets/images/app_logo_full.png"
  platforms:
    android:
      enable: true
      # adaptive_background_color: '#ffffff'
      # adaptive_background_image: 'assets/ic_background.png'
      # adaptive_foreground_image: 'assets/ic_foreground.png'
      # adaptive_round_image: 'assets/ic_logo_round.png'
      # adaptive_monochrome_image: 'assets/ic_logo_monochrome.png'
    ios:
      enable: false
    web:
      enable: true
      # image_path: 'assets/ic_logo_border.png'
      # favicon_path: 'assets/ic_logo_round.png'
    macos:
      enable: false
    windows:
      enable: true
      # image_path: 'assets/ic_logo_border.png'
    linux:
      enable: true
      # image_path: 'assets/ic_logo_border.png'

# dart run names_launcher:change
names_launcher:
  name: "EduMigSoft Manager System"
  platforms:
    android:
      enable: true
      name: "EMS System"
    ios:
      enable: false
      # name: "Your iOS App Name"
    web:
      enable: true
      name: "EduMigSoft_Manager_System"
    macos:
      enable: false
      # name: "Your MasOS App Name"
    windows:
      enable: true
      name: "EduMigSoft_Manager_System"
    linux:
      enable: false
      name: "EduMigSoft_Manager_System"
