name: localizations_server
description: Server implementation for Localizations.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  localizations_shared:
    path: ../localizations_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
