name: localizations_server
description: Server implementation for Localizations.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  localizations_shared:
    path: ../localizations_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
