name: zard_form
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  zard: ^0.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
