services:
  ems_postgres_db:
    build: .
    container_name: ems_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: A.N-shgS.f2D~n5j
    ports:
      - 5432:5432
    volumes:
      - ems_postgres_data:/var/lib/postgresql/data
    command: >
      -c shared_preload_libraries=pg_cron
volumes:
  ems_postgres_data:
  