name: ems_system
publish_to: none

environment:
  sdk: ^3.10.7

workspace:
  # Servers
  - servers/ems/server_v1
  - servers/sms/server_v1

  # Apps
  - apps/ems/app_v1
  - apps/ems/app_design_draft
  - apps/sms/app_v1

  # Core
  - packages/core/core_client
  - packages/core/core_server
  - packages/core/core_shared
  - packages/core/core_ui

  # Design System
  # - packages/design_system/design_system_client
  # - packages/design_system/design_system_server
  - packages/design_system/design_system_shared
  - packages/design_system/design_system_ui

  # Images
  # - packages/images/images_client
  # - packages/images/images_server
  # - packages/images/images_shared
  - packages/images/images_ui

  # Localization
  # - packages/localization/localization_client
  - packages/localizations/localizations_server
  - packages/localizations/localizations_shared
  - packages/localizations/localizations_ui

  # Open API
  # - packages/open_api/open_api_client
  - packages/open_api/open_api_server
  - packages/open_api/open_api_shared
  # - packages/open_api/open_api_ui

  # User
  - packages/user/user_client
  - packages/user/user_server
  - packages/user/user_shared
  - packages/user/user_ui

  # Auth
  - packages/auth/auth_client
  - packages/auth/auth_server
  - packages/auth/auth_shared
  - packages/auth/auth_ui

  # ProjectCore
  # - packages/project/project_core/project_core_client
  # - packages/project/project_core/project_core_server
  - packages/project/project_core/project_core_shared
  - packages/project/project_core/project_core_ui

  # # Project
  # - packages/project/project_client
  # - packages/project/project_server
  # - packages/project/project_shared
  # - packages/project/project_ui

  # Notebook
  - packages/notebook/notebook_client
  - packages/notebook/notebook_server
  - packages/notebook/notebook_shared
  - packages/notebook/notebook_ui

  # # Tag
  - packages/tag/tag_client
  - packages/tag/tag_server
  - packages/tag/tag_shared
  - packages/tag/tag_ui

  # # Task
  # - packages/task/task_client
  # - packages/task/task_server
  # - packages/task/task_shared
  # - packages/task/task_ui
