name: user_server
description: Server implementation for User Management.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  drift: ^2.30.0
  core_shared:
    path: ../../core/core_shared
  core_server:
    path: ../../core/core_server
  open_api_shared:
    path: ../../open_api/open_api_shared
  user_shared:
    path: ../user_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: 2.10.4
  drift_dev: ^2.30.0
