services:
  sms_server:
    container_name: sms_server_dev
    image: sms_server_image:latest
    build:
      context: ../../../
      dockerfile: servers/sms/container/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ems_system_net
    labels:
      com.ems.service: "sms-server"
      com.ems.environment: "development"

networks:
  ems_system_net:
    external: true
