name: core_shared
description: Core Shared Package (Pure Dart)
publish_to: none
version: 1.0.0
repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.17.0
  logging: ^1.3.0
  path: ^1.9.1
  zard: ^0.0.25
  get_it: ^9.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
