name: tag_ui
description: Flutter UI implementation for tag management feature
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  tag_shared: ^1.1.0
  tag_client: ^1.1.0
  core_shared: ^1.1.0
  core_ui: ^1.1.0
  design_system_ui: ^1.1.0
  localizations_ui: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
