name: images_ui
description: "Images UI Package"
publish_to: none
version: 0.1.0
# homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: StudentIcon
  #     fonts:
  #       - asset: assets/fonts/StudentIcon.ttf

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
