name: open_api_server
description: OpenAPI Server (Swagger UI)
publish_to: none
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # reflectable: ^5.0.1
  core_shared:
    path: ../../core/core_shared
  core_server:
    path: ../../core/core_server
  open_api_shared:
    path: ../open_api_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
