name: open_api_server
description: OpenAPI Server (Swagger UI)
publish_to: none
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_shared
  ems_system_core_server:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_server
  open_api_shared:
    path: ../open_api_shared

dependency_overrides:
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      path: core_shared
      ref: refactor/new_structure

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
