name: tag_shared
description: Core domain logic and entities for tag management feature
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.17.0
  core_shared:
    path: ../../../core/core_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
