name: auth_client
description: Client implementation for Authentication.
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  dio: ^5.0.0
  retrofit: 4.9.1
  core_shared: ^1.1.0
  core_client: ^1.1.0
  auth_shared: ^1.1.0
  user_shared: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  mocktail: ^1.0.0
  build_runner: ^2.10.5
  retrofit_generator: ^10.2.0
  analyzer: ^8.4.1
