name: school_ui
description: "School UI Package"
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0
  get_it: ^9.2.0
  provider: ^6.1.5+1
  core_shared: ^1.1.0
  core_ui: ^1.1.0
  school_shared: ^1.1.0
  school_client: ^1.1.0
  design_system_shared: ^1.1.0
  design_system_ui: ^1.1.0
  localizations_ui: ^1.1.0
  localizations_shared: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0
  matcher: ^0.12.16

flutter:
  uses-material-design: true
