name: notebook_ui
description: UI Package for Notebook Management.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  get_it: ^9.2.0
  dio: ^5.9.0
  core_shared:
    path: ../../core/core_shared
  core_client:
    path: ../../core/core_client
  core_ui:
    path: ../../core/core_ui
  design_system_shared:
    path: ../../design_system/design_system_shared
  design_system_ui:
    path: ../../design_system/design_system_ui
  localizations_ui:
    path: ../../localizations/localizations_ui
  localizations_shared:
    path: ../../localizations/localizations_shared
  zard_form:
    path: ../../zard_form
  notebook_shared:
    path: ../notebook_shared
  notebook_client:
    path: ../notebook_client
  auth_client:
    path: ../../auth/auth_client
  auth_ui:
    path: ../../auth/auth_ui
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.10.5
