name: notebook_ui
description: UI Package for Notebook Management.
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  get_it: ^9.2.0
  dio: ^5.9.0
  file_picker: ^10.3.10
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  pdfx: ^2.9.2
  permission_handler: ^11.3.0
  core_shared: ^1.1.0
  core_client: ^1.1.0
  core_ui: ^1.1.0
  design_system_shared: ^1.1.0
  design_system_ui: ^1.1.0
  localizations_ui: ^1.1.0
  localizations_shared: ^1.1.0
  zard_form:
    path: ../../zard_form
  notebook_shared: ^1.1.0
  notebook_client: ^1.1.0
  tag_shared: ^1.1.0
  tag_client: ^1.1.0
  tag_ui: ^1.1.0
  auth_client: ^1.1.0
  auth_ui: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.10.5
