name: design_system_ui
description: UI Package for Design System.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  logging: ^1.3.0
  get_it: ^9.2.0
  core_ui:
    path: ../../core/core_ui
  design_system_shared:
    path: ../design_system_shared
  localizations_ui:
    path: ../../localizations/localizations_ui
  images_ui:
    path: ../../images/images_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
