name: design_system_ui
description: UI Package for Design System.
publish_to: none
version: 1.1.0

# repository:

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  logging: ^1.3.0
  get_it: ^9.2.0
  core_ui: ^1.1.0
  design_system_shared: ^1.1.0
  localizations_ui: ^1.1.0
  images_ui: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
