name: school_server
description: Server implementation for school management.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  drift: ^2.30.0
  school_shared:
    path: ../school_shared
  core_server:
    path: ../../core/core_server
  core_shared:
    path: ../../core/core_shared
  open_api_shared:
    path: ../../open_api/open_api_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  build_runner: ^2.10.5
  drift_dev: ^2.30.0
  mocktail: ^1.0.4
