name: open_api_shared
description: OpenAPI Shared (Swagger UI)
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  reflectable: ^5.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
