name: tag_ui
description: Flutter UI implementation for tag management feature
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  tag_shared:
    path: ../tag_shared
  tag_client:
    path: ../tag_client
  core_shared:
    path: ../../../core/core_shared
  core_ui:
    path: ../../../core/core_ui
  design_system_ui:
    path: ../../../design_system/design_system_ui
  localizations_ui:
    path: ../../../localizations/localizations_ui
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
