name: core_server
description: Core Server Package (Infrastructure)
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  bcrypt: ^1.2.0
  dart_jsonwebtoken: ^3.3.1
  drift: ^2.30.0
  drift_postgres: ^1.3.1
  postgres: ^3.5.9
  pointycastle: 4.0.0
  core_shared:
    path: ../core_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
  build_runner: 2.10.4
