name: auth_server
description: Server implementation for Authentication.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  drift: ^2.30.0
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_shared
  ems_system_core_server:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_server
  open_api_shared:
    path: ../../open_api/open_api_shared
  user_shared:
    path: ../../user/user_shared
  user_server:
    path: ../../user/user_server
  auth_shared:
    path: ../auth_shared

dependency_overrides:
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      path: core_shared
      ref: refactor/new_structure

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: 2.10.4
  drift_dev: ^2.30.0
  mocktail: ^1.0.4
