name: app_design_draft
description: "A new Flutter project."
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core_shared:
    path: ../../../packages/core/core_shared
  core_ui:
    path: ../../../packages/core/core_ui
  design_system_shared:
    path: ../../../packages/design_system/design_system_shared
  design_system_ui:
    path: ../../../packages/design_system/design_system_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  envied_generator: ^1.3.2

flutter:
  uses-material-design: true
