name: core_ui
description: "Core UI Package"
publish_to: none
version: 1.0.0

repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  zard: ^0.0.25
  core_shared:
    path: ../core_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
