name: core_ui
description: "Core UI Package"
publish_to: none
version: 0.1.0
# homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  path_provider: ^2.1.5
  zard: ^0.0.25
  core_shared:
    path: ../core_shared
  design_system_shared:
    path: ../../design_system/design_system_shared
  design_system_ui:
    path: ../../design_system/design_system_ui
  # localizations_ui:
  #   path: ../../localizations_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.4
