name: school_shared
description: Shared entities and logic for school management.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.11.0
  zard: ^0.0.25
  core_shared:
    path: ../../core/core_shared
  open_api_shared:
    path: ../../open_api/open_api_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  mocktail: ^1.0.4
