name: localizations_shared
description: Shared localizations.
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
