name: localizations_shared
description: Shared localizations.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
