name: design_system_shared
description: Shared design system.
publish_to: none
version: 1.1.0

# repository:

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
