name: notebook_client
description: HTTP client implementation for notebook management feature
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  dio: ^5.0.0
  retrofit: 4.9.1
  json_annotation: ^4.9.0
  notebook_shared: ^1.0.0
  core_shared: ^1.0.0
  core_client: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  mockito: ^5.4.4
  build_runner: ^2.10.5
  retrofit_generator: 10.2.0
  json_serializable: ^6.9.2
