name: app_v1
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^1.3.2
  dio: ^5.9.0
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_shared
  ems_system_core_ui:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_ui
  localizations_ui:
    path: ../../packages/localizations/localizations_ui
  design_system_shared:
    path: ../../packages/design_system/design_system_shared
  design_system_ui:
    path: ../../packages/design_system/design_system_ui
  auth_ui:
    path: ../../packages/auth/auth_ui
  auth_client:
    path: ../../packages/auth/auth_client
  user_ui:
    path: ../../packages/user/user_ui
  user_client:
    path: ../../packages/user/user_client

dependency_overrides:
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      path: core_shared
      ref: refactor/new_structure

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.4
  envied_generator: ^1.3.2

flutter:
  uses-material-design: true
