name: app_v1
description: "A new Flutter project."
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^1.3.2
  dio: ^5.9.0
  core_shared:
    path: ../../packages/core/core_shared
  core_ui:
    path: ../../packages/core/core_ui
  localizations_ui:
    path: ../../packages/localizations/localizations_ui
  design_system_shared:
    path: ../../packages/design_system/design_system_shared
  design_system_ui:
    path: ../../packages/design_system/design_system_ui
  auth_ui:
    path: ../../packages/auth/auth_ui
  auth_client:
    path: ../../packages/auth/auth_client
  user_ui:
    path: ../../packages/user/user_ui
  user_client:
    path: ../../packages/user/user_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  envied_generator: ^1.3.2

flutter:
  uses-material-design: true
