name: sms_server_v1
description: SMS System Server V1
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  envied: ^1.3.2
  reflectable: ^5.1.0
  dart_jsonwebtoken: ^3.3.1
  logging: ^1.3.0
  get_it: ^9.2.0
  core_shared: ^1.1.0
  core_server: ^1.1.0
  open_api_shared: ^1.1.0
  open_api_server: ^1.1.0
  auth_server: ^1.1.0
  user_server: ^1.1.0
  school_server: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  build_runner: ^2.10.5
  envied_generator: ^1.3.2
  mocktail: ^1.0.4
  reflectable_builder: ^1.1.0
