name: user_shared
description: Shared entities and logic for User Management.
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: 1.17.0
  zard: ^0.0.25
  core_shared: ^1.1.0
  open_api_shared: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
