name: project_core_shared
description: ProjectCore entities and logic for Project.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

# dependencies:
#   meta: ^1.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
