name: auth_shared
description: Shared models and contracts for Authentication.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  meta: ^1.17.0
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_shared
  user_shared:
    path: ../../user/user_shared
  open_api_shared:
    path: ../../open_api/open_api_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
