name: auth_shared
description: Shared models and contracts for Authentication.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: ^1.17.0
  core_shared:
    path: ../../core/core_shared
  user_shared:
    path: ../../user/user_shared
  open_api_shared:
    path: ../../open_api/open_api_shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
