name: tag_server
description: Server implementation for tag management feature
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  tag_shared: ^1.1.0
  core_shared: ^1.1.0
  core_server: ^1.1.0
  auth_server: ^1.1.0
  auth_shared: ^1.1.0
  drift: ^2.23.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  drift_dev: ^2.23.0
  build_runner: ^2.10.5
