name: auth_ui
description: UI Package for Authentication.
publish_to: none
version: 1.1.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  get_it: ^9.2.0
  core_shared: ^1.1.0
  core_client: ^1.1.0
  core_ui: ^1.1.0
  design_system_shared: ^1.1.0
  localizations_ui: ^1.1.0
  zard_form:
    path: ../../zard_form
  auth_shared: ^1.1.0
  auth_client: ^1.1.0
  user_shared: ^1.1.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
