name: auth_ui
description: UI Package for Authentication.
publish_to: none
version: 1.0.0

# repository: https://github.com/edumigsoft/ems_system_core

resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  get_it: ^9.2.0
  core_shared:
    path: ../../core/core_shared
  core_client:
    path: ../../core/core_client
  core_ui:
    path: ../../core/core_ui
  design_system_shared:
    path: ../../design_system/design_system_shared
  localizations_ui:
    path: ../../localizations/localizations_ui
  zard_form:
    path: ../../zard_form
  auth_shared:
    path: ../auth_shared
  auth_client:
    path: ../auth_client
  user_shared:
    path: ../../user/user_shared
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
