name: user_ui
description: UI Package for User Management.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  get_it: ^9.2.0
  dio: ^5.9.0
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_shared
  ems_system_core_client:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_client
  ems_system_core_ui:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      ref: refactor/new_structure
      path: core_ui
  design_system_shared:
    path: ../../design_system/design_system_shared
  design_system_ui:
    path: ../../design_system/design_system_ui
  localizations_ui:
    path: ../../localizations/localizations_ui
  localizations_shared:
    path: ../../localizations/localizations_shared
  zard_form:
    path: ../../zard_form
  user_shared:
    path: ../user_shared
  user_client:
    path: ../user_client
  auth_client:
    path: ../../auth/auth_client

dependency_overrides:
  ems_system_core_shared:
    git:
      url: git@github.com:edumigsoft/ems_system_core.git
      path: core_shared
      ref: refactor/new_structure

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.4
